apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: cloudops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: 270254976698.dkr.ecr.ap-south-1.amazonaws.com/cloudops-notification-service:latest
          ports:
            - containerPort: 5001
