apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: cloudops
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
